// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __PK1_RcppExports_h__
#define __PK1_RcppExports_h__

#include <Rcpp.h>

namespace PK1 {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("PK1", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("PK1", "PK1_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in PK1");
            }
        }
    }

    inline NumericVector filter1_tv(NumericVector rho, NumericVector x, double y0 = 0) {
        typedef SEXP(*Ptr_filter1_tv)(SEXP,SEXP,SEXP);
        static Ptr_filter1_tv p_filter1_tv = NULL;
        if (p_filter1_tv == NULL) {
            validateSignature("NumericVector(*filter1_tv)(NumericVector,NumericVector,double)");
            p_filter1_tv = (Ptr_filter1_tv)R_GetCCallable("PK1", "PK1_filter1_tv");
        }
        RObject __result;
        {
            RNGScope __rngScope;
            __result = p_filter1_tv(Rcpp::wrap(rho), Rcpp::wrap(x), Rcpp::wrap(y0));
        }
        if (__result.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (__result.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(__result).c_str());
        return Rcpp::as<NumericVector >(__result);
    }

}

#endif // __PK1_RcppExports_h__
