// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// FilterTV1
NumericVector FilterTV1(NumericVector rho, NumericVector x, double y0);
RcppExport SEXP _PK1_FilterTV1(SEXP rhoSEXP, SEXP xSEXP, SEXP y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y0(y0SEXP);
    rcpp_result_gen = Rcpp::wrap(FilterTV1(rho, x, y0));
    return rcpp_result_gen;
END_RCPP
}
// PK1_Sim
NumericMatrix PK1_Sim(int nReps, NumericVector X0, NumericVector Dose, NumericVector tObs, NumericVector Cl, NumericVector Ka, NumericVector Ke, NumericVector sigmaP);
RcppExport SEXP _PK1_PK1_Sim(SEXP nRepsSEXP, SEXP X0SEXP, SEXP DoseSEXP, SEXP tObsSEXP, SEXP ClSEXP, SEXP KaSEXP, SEXP KeSEXP, SEXP sigmaPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Dose(DoseSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tObs(tObsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cl(ClSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ka(KaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ke(KeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigmaP(sigmaPSEXP);
    rcpp_result_gen = Rcpp::wrap(PK1_Sim(nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP));
    return rcpp_result_gen;
END_RCPP
}
// PK1_Cmax_Sim
NumericMatrix PK1_Cmax_Sim(int nReps, NumericVector X0, NumericVector Dose, NumericVector tObs, NumericVector Cl, NumericVector Ka, NumericVector Ke, NumericVector sigmaP);
RcppExport SEXP _PK1_PK1_Cmax_Sim(SEXP nRepsSEXP, SEXP X0SEXP, SEXP DoseSEXP, SEXP tObsSEXP, SEXP ClSEXP, SEXP KaSEXP, SEXP KeSEXP, SEXP sigmaPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Dose(DoseSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tObs(tObsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Cl(ClSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ka(KaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ke(KeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigmaP(sigmaPSEXP);
    rcpp_result_gen = Rcpp::wrap(PK1_Cmax_Sim(nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_stan_fit4PK1_Fixed_ODE_Noise_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4PK1_Fixed_SDE_Noise_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4PK1_Fixed_SDE_Pure_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4PK1_Mixed_ODE_Noise_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4PK1_Mixed_SDE_Noise_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4PK1_Mixed_SDE_Pure_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_PK1_FilterTV1", (DL_FUNC) &_PK1_FilterTV1, 3},
    {"_PK1_PK1_Sim", (DL_FUNC) &_PK1_PK1_Sim, 8},
    {"_PK1_PK1_Cmax_Sim", (DL_FUNC) &_PK1_PK1_Cmax_Sim, 8},
    {"_rcpp_module_boot_stan_fit4PK1_Fixed_ODE_Noise_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PK1_Fixed_ODE_Noise_mod, 0},
    {"_rcpp_module_boot_stan_fit4PK1_Fixed_SDE_Noise_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PK1_Fixed_SDE_Noise_mod, 0},
    {"_rcpp_module_boot_stan_fit4PK1_Fixed_SDE_Pure_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PK1_Fixed_SDE_Pure_mod, 0},
    {"_rcpp_module_boot_stan_fit4PK1_Mixed_ODE_Noise_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PK1_Mixed_ODE_Noise_mod, 0},
    {"_rcpp_module_boot_stan_fit4PK1_Mixed_SDE_Noise_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PK1_Mixed_SDE_Noise_mod, 0},
    {"_rcpp_module_boot_stan_fit4PK1_Mixed_SDE_Pure_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PK1_Mixed_SDE_Pure_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_PK1(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
