# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter1.tv <- function(rho, x, y0 = 0) {
    .Call(`_PK1_FilterTV1`, rho, x, y0)
}

.PK1_Sim <- function(nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP) {
    .Call(`_PK1_PK1_Sim`, nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP)
}

.PK1_Cmax_Sim <- function(nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP) {
    .Call(`_PK1_PK1_Cmax_Sim`, nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP)
}

