# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter1.tv <- function(rho, x, y0 = 0) {
    .Call('PK1_Filter1_TV', PACKAGE = 'PK1', rho, x, y0)
}

.PK1_Sim <- function(nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP) {
    .Call('PK1_PK1_Sim', PACKAGE = 'PK1', nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP)
}

.PK1_Cmax_Sim <- function(nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP) {
    .Call('PK1_PK1_Cmax_Sim', PACKAGE = 'PK1', nReps, X0, Dose, tObs, Cl, Ka, Ke, sigmaP)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('PK1_RcppExport_registerCCallable', PACKAGE = 'PK1')
})
